name: TodoSync

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0-14/1,22,23 * * *'

jobs:
  sync:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Branch Filestorage Action
      uses: moonrailgun/branch-filestorage-action@v1.2.2
      with:
        branch: graphtoken
        path: graphtoken.asc
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build .\TodoSynchronizer.CLI\TodoSynchronizer.CLI.csproj --no-restore -c Release
    - name: Run
      run: .\TodoSynchronizer.CLI\bin\Release\net6.0\TodoSynchronizer.CLI.exe -canvastoken ${{ secrets.CANVAS_TOKEN }} -graphtokenfile graphtoken.asc -configfile config.yaml -graphtokenkey ${{ secrets.KEY }}
